-- MySQL Script generated by MySQL Workbench
-- Wed Nov  2 00:58:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cade_meu_dinheiro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cade_meu_dinheiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cade_meu_dinheiro` DEFAULT CHARACTER SET utf8 ;
USE `cade_meu_dinheiro` ;

-- -----------------------------------------------------
-- Table `cade_meu_dinheiro`.`carteiras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cade_meu_dinheiro`.`carteiras` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `value` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cade_meu_dinheiro`.`orcamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cade_meu_dinheiro`.`orcamentos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `value` DECIMAL(8,2) NOT NULL,
  `option` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cade_meu_dinheiro`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cade_meu_dinheiro`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cade_meu_dinheiro`.`transacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cade_meu_dinheiro`.`transacoes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `option` INT NOT NULL,
  `value` DECIMAL(8,2) NOT NULL,
  `date` DATE NOT NULL,
  `carteira_id` INT UNSIGNED NOT NULL,
  `orcamento_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `carteira_id`, `orcamento_id`),
  INDEX `fk_transacoes_carteiras_idx` (`carteira_id` ASC),
  INDEX `fk_transacoes_orcamentos1_idx` (`orcamento_id` ASC),
  CONSTRAINT `fk_transacoes_carteiras`
    FOREIGN KEY (`carteira_id`)
    REFERENCES `cade_meu_dinheiro`.`carteiras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacoes_orcamentos1`
    FOREIGN KEY (`orcamento_id`)
    REFERENCES `cade_meu_dinheiro`.`orcamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
